[general]
seed         = 1234

[catalog]
outdir       = "./results/data/"
catalog_tag  = "bbh_1k"
n_events     = 1000
z_cut        = 10.0

[deviations]
pn_orders    = ["-1"]
mu_vec        = [0.000001, 0.000002, 0.000003, 0.000004, 0.000005, 0.000006, 0.000007, 0.000008, 0.000009, 0.00001]
sigma_vec     = [0.000001, 0.000002, 0.000003, 0.000004, 0.000005, 0.000006, 0.000007, 0.000008, 0.000009, 0.00001]

[detectors]
network      = "ET_45_15km"

[fisher]
waveform               = ["PhenomHM"]
fmin                   = 2.0

[population]
snr_threshold          = 12.0
snr_inspiral_threshold = 6.0

[bootstrap]
outdir        = "./results/data/"
bootstrap_tag = "bbh_200k"
n_catalog     = 9
n_sample      = 1000

[grid]
grid_tag      = "void"
n_median      = 150

[plots]
plot_tag      = "bbh_1k_grid"
outdir        = "./results/plots/"
