[general]
seed         = 1234

[catalog]
outdir       = "./results/data/"
catalog_tag  = "ET15km45_bbh_200k"
n_events     = 200000
z_cut        = inf

[deviations]
pn_orders    = ["-1", "0", "0.5", "1", "1.5", "2", "log(2.5)", "3", "log(3.)", "3.5"]
mu           = [ 0.0, 0.0,   0.0, 0.0,   0.0, 0.0,        0.0, 0.0,       0.0,   0.0]
sigma        = [ 0.0, 0.0,   0.0, 0.0,   0.0, 0.0,        0.0, 0.0,       0.0,   0.0]

[detectors]
network      = "ET_45_15km"

[fisher]
waveform               = ["PhenomD", "PhenomHM"]
fmin                   = 2.0

[population]
snr_threshold           = 12.0
snr_inspiral_threshold  = 6.0
select_before_bootstrap = false

[bootstrap]
outdir        = "./results/data/"
bootstrap_tag = "ET15km45_bbh_200k_bts_10k"
n_catalog     = 10000
n_sample      = 1000

[plots]
outdir        = "./results/plots/"
plot_tag      = "ET15km45_bbh_200k_PhenomHM_realization_1"

[plots.fig8]
waveform_family = "PhenomHM"
grid_points = 700
credible_interval = 0.90
n_events = 100000
number_of_events_single_realization = 10000
n_events_and_number_of_events_single_realization_refer_directly_to_observed_events = false
realization_index = 2
use_inspiral_snr_threshold = false
pn_orders = ["-1", "0", "0.5", "1", "1.5", "2", "3", "3.5", "log(2.5)", "log(3.)"]
minus_one_pn_scale = 1000.0
inset_axis_scale = 10.0
main_x_limits = [-0.010, 0.020]
main_y_limits = [0.0, 0.050]
inset_x_limits = [-0.001, 0.001]
inset_y_limits = [0.0, 0.002]
