[general]
seed = 1234
outdir = "./results/data/"

[catalog]
catalog_tag = "gw150914_like"
n_events = 100
z_cut = inf

[gw150914_like]
mc = 30.0
eta = 0.247
dL = 0.4
redshift = 0.09
spin_range = [-0.3, 0.3]
theta_cos_range = [-1.0, 1.0]
phi_range = [0.0, 6.283185307179586]
iota_cos_range = [-1.0, -0.7071067811865476]
psi_range = [0.0, 3.141592653589793]
t_coal_range = [0.0, 1.0]
phi_coal_range = [0.0, 6.283185307179586]

[deviations]
pn_orders = ["-1", "0", "0.5", "1", "1.5", "2", "log(2.5)", "3", "log(3.)", "3.5"]
mu = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
sigma = [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

[detectors]
network = "ETS"

[fisher]
waveform = ["PhenomHM"]

[population]
snr_threshold = 12.0
snr_inspiral_threshold = 0.0
select_before_bootstrap = true

[fmin_comparison]
fmin_values = [2.0, 5.0, 10.0, 15.0, 20.0]

[bootstrap]
outdir = "results/data/"
bootstrap_tag = "gw150914_like"
n_catalog = 1
n_sample = 1000

[plots]
outdir = "results/plots/"
plot_tag = "gw150914_like"
waveform = "PhenomHM"
events_per_realization = 1
compute_mean_std_dev_in_log_space = true
y_limits_minus_one = [8e-7, 1e-3]
y_limits_remaining = [5e-6, 8e-1]
