[general]
seed         = 1234

[catalog]
outdir       = "./results/data/"
catalog_tag  = "bbh_200k"
n_events     = 200000
z_cut        = 1000

[deviations]
pn_orders    = ["-1", "0", "0.5", "1", "1.5", "2", "log(2.5)", "3", "log(3.)", "3.5"]
mu           = [ 0.0, 0.0,   0.0, 0.0,   0.0, 0.0,        0.0, 0.0,       0.0,   0.0]
sigma        = [ 0.0, 0.0,   0.0, 0.0,   0.0, 0.0,        0.0, 0.0,       0.0,   0.0]

[detectors]
network      = "LHV"

[fisher]
waveform               = ["PhenomD","PhenomHM"]
fmin                   = 20.0

[population]
snr_threshold           = 12.0
snr_inspiral_threshold  = 6.0
select_before_bootstrap = true

[bootstrap]
outdir        = "./results/data/"
bootstrap_tag = "bbh_200k"
n_catalog     = 9
n_sample      = 1000

[plots]
plot_tag      = "bbh_200k"
outdir        = "./results/plots/"
