header=leheader

; ### Global parameter for the whole simulation
[global]
simulation_tag=template

; ### Parameter for the specific scripts ####################################### 
[a_run_catalog]
network=ETS
n_events=100

[to_be_deleted]
jeff=jeff