using Colors

function color_on_white(color, alpha::Real)
    rgb = RGB{Float64}(color)
    a = Float64(alpha)
    return RGB{Float64}(
        a * red(rgb) + (1.0 - a),
        a * green(rgb) + (1.0 - a),
        a * blue(rgb) + (1.0 - a),
    )
end

const FIG9_IMPROVEMENT_COLORMAP = [
    "#E86A17",
    "#D46B24",
    "#BF6B32",
    "#A76943",
    "#8F6556",
    "#75637A",
    "#5F6B98",
    "#4973B6",
    "#347BC7",
    "#1E6CCB",
]
const FIG9_IMPROVEMENT_COLORS = RGB{Float64}.(parse.(Ref(Colorant), FIG9_IMPROVEMENT_COLORMAP))
const FIG9_LIGHT_IMPROVEMENT_COLORMAP_ALPHA = 0.4
const FIG9_LIGHT_IMPROVEMENT_COLORMAP = color_on_white.(FIG9_IMPROVEMENT_COLORS, FIG9_LIGHT_IMPROVEMENT_COLORMAP_ALPHA)
const FIG9_IMPROVEMENT_LOW_COLOR = first(FIG9_IMPROVEMENT_COLORS)
const FIG9_IMPROVEMENT_MIDDLE_COLOR = FIG9_IMPROVEMENT_COLORS[(length(FIG9_IMPROVEMENT_COLORS) ÷ 2) + 1]
const FIG9_IMPROVEMENT_HIGH_COLOR = last(FIG9_IMPROVEMENT_COLORS)
const FIG9_LIGHT_IMPROVEMENT_LOW_COLOR = first(FIG9_LIGHT_IMPROVEMENT_COLORMAP)
const FIG9_LIGHT_IMPROVEMENT_MIDDLE_COLOR = FIG9_LIGHT_IMPROVEMENT_COLORMAP[(length(FIG9_LIGHT_IMPROVEMENT_COLORMAP) ÷ 2) + 1]
const FIG9_LIGHT_IMPROVEMENT_HIGH_COLOR = last(FIG9_LIGHT_IMPROVEMENT_COLORMAP)

const FIG9_POPULATION_CONTOUR_COLORMAP = ["#F7F7F7", "#E0E0E0", "#BDBDBD"]
const FIG9_POPULATION_CONTOUR_LINE_COLOR = "#8F8F8F"
const FIG9_POPULATION_HIST_FILL_COLOR = "#D9D9D9"
const FIG9_POPULATION_HIST_EDGE_COLOR = FIG9_POPULATION_CONTOUR_LINE_COLOR
const FIG9_POPULATION_HIST_OUTLINE_COLOR = :black
